catalog:
  '@antfu/eslint-config': ^4.12.0
  '@compose/config-vite-fragment': ^1.0.8
  '@compose/eslint-config': ^0.0.95
  '@compose/eslint9-config': ^1.0.0
  '@compose/tsconfig': ^1.0.3
  '@tsconfig/node22': ^22.0.1
  '@types/node': ^22.14.1
  chalk: ^5.4.1
  commander: ^13.1.0
  inquirer: ^12.5.2
  jiti: ^2.4.2
  npm-run-all: ^4.1.5
  typescript: ^5.8.3
  vite: ^6.3.2
  vite-plugin-dts: ^4.5.3
  vitest: ^3.1.1
  vue-tsc: ^2.2.8
