catalog:
  '@antfu/eslint-config': ^4.12.0
  '@compose/config-vite-fragment': ^1.0.10
  '@compose/eslint9-config': ^1.0.1
  '@compose/tsconfig': ^1.0.3
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-url': ^8.0.2
  '@rollup/plugin-virtual': ^3.0.2
  '@tsconfig/node22': ^22.0.1
  '@types/node': ^22.14.1
  chalk: ^5.4.1
  commander: ^13.1.0
  eslint: ^9.25.0
  fast-glob: ^3.3.3
  inquirer: ^12.5.2
  jiti: ^2.4.2
  npm-run-all: ^4.1.5
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^6.3.2
  vitest: ^3.1.2
  vue-tsc: ^2.2.8
